name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - run: npm run build --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Current directory: $(pwd)"
            echo "Changing to home directory"
            cd ~
            echo "Current directory: $(pwd)"
            echo "Changing to node_ci directory"
            cd node_ci
            echo "Current directory: $(pwd)"
            echo "Pulling latest changes"
            git pull origin main
            echo "Installing dependencies"
            npm install
            echo "Building project (if build script exists)"
            npm run build --if-present
            echo "Restarting application with PM2"
            pm2 restart node_ci || pm2 start index.js --name node_ci
            echo "Deployment completed"
